FROM python:3.11-slim-buster

COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

WORKDIR /ablive-server

COPY app app/

COPY serve.sh ./
RUN chmod +x ./serve.sh

EXPOSE 7772

CMD ["bash", "./serve.sh"]
