FROM python:3.10-slim-buster

COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

WORKDIR /ablive-server

COPY app app/

COPY serve.sh ./
RUN chmod +x ./serve.sh

EXPOSE 7772

CMD ["bash", "./serve.sh"]
