[package]
name = "ablive-scheduler-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = "2.6"
futures = "0.3"
tokio = "1"
serde = "1"
bson = "2"
config = "0.13"
